<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Form1 - backup of old version.cs" />
    <Compile Remove="Form1 - backup of original clean slate version .cs" />
    <Compile Remove="Form1-copy.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PiperSharp" Version="1.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="app.ico" />
  </ItemGroup>

</Project>
